baseURL = 'http://localhost:57491/'
languageCode = "vi" 
title = "Duy's JS Insight" 
theme = "hugo-theme-stack"

[params]
      assetsDir = "assets"

    mainSections = ["posts"]
    
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3